### ISSUE TITLE
Critical vital update to 0.5.3 kernel to fix bug :  "all copy/paste and drag and drop functions on the downloader don't work" !

### ISSUE THREAD

**Issue by trimechee** [helloyanis/media-downloader-unleashed#6]
Hi, I don't want to tire you again Mr Helloyanis especially since you were so generous  to make us a new awesome version recently, but Live stream downloader has made again another new version to fix serious bugs: "all copy/paste and drag and drop functions on the downloader don't work" !

the dream is update to kernel 0.5.3 please to fix these serious bugs, thanks !

**Comment by helloyanis** [comment]
Hello!

After some trial and error I could update the extension to work with manifest v3 on Firefox with the latest changes from upstream. However this might break support for older firefox versions, but it means you can install it on other browsers like Chrome (without going through the store). I have not tried it on Chrome though, so it could break at any time!

I have also added [a release page](https://github.com/helloyanis/file-downloader-unleashed/releases/latest) for easy access to the .xpi file!

Don't forget to close the issue if that fixed it for you.

**Comment by helloyanis** [comment]
I have updated the add-on to the latest version and also improved a few things like adding the option to keep your screen turned on while downloading (original version just disables this on Firefox) and remembering this option even after you close the add-on, tell me what you think of it! (Option `Keep awake` in the add-ons settings)

**Comment by helloyanis** [comment]
Hello,
You should be able to use [Firefox Extended Support Release](https://www.mozilla.org/firefox/all/desktop-esr/) for Windows 7, can't you? It's a version of Firefox made to work with older computer such as windows 7 ones.

Also, if you want to install manually on a chromium browser, you can always get the xpi file from [the releases page](https://github.com/helloyanis/media-downloader-unleashed/releases). XPI, CRX are both the same file type, they are just zip files with renamed extensions so you can try to rename it your browser does not install it!
